### PR TITLE
reflagger program rewrite

### PR DESCRIPTION
**Pull request by cuantar**
Here is my rewrite of the re-flagger program.
Its behavior differs slightly from the original, so both algorithms are run currently.
The new version files have extension `*.new` --- *for now*, until it's been vetted.

### CODE REVIEW

**Comment by cuantar** [comment]
I've noticed something weird.
For some reason, my version is setting `-fe L-wide` for every line in the file, instead of preserving the `-fe S-wide` lines.  the new `diff` technique using `git diff` made it obvious.  I'll fix it!

**Comment by cuantar** [comment]
... should now be fixed.  The only differences now between the two programs' outputs are additional flags, not changes to already-existing ones.

**Comment by cuantar** [comment]
I added a `-d` command line flag to turn the `diff` output on.  Eventually we can remove the legacy code and also the diff.

**Comment by JPGlaser** [comment]
Closing as its a stale merge.

**Pull request closed without merging**
